config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  devise_for :users,
             skip: :registrations,
             controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  devise_scope :user do
    resource :registration,
             only: [:edit, :update],
             controller: "users/registrations",
             as: :user_registration

    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end

  resource :my_group, except: [:new, :edit, :create] do
    resources :invitations, only: [:create] do
      collection do
        get :commit
      end
    end
  end
  resources :groups, only: [:index]

  namespace :library do
    resources :nominations, only: [:create], param: :slug
  end

  resources :movies, except: [:new, :edit], param: :slug
  resources :tv_shows, except: [:new, :edit], param: :slug

  resources :votes, only: :update, param: :slug
  resources :comments, only: :create, param: :slug

  resource :pick, only: [:new, :create, :show]

  resource :search, only: :show
  resource :faq, only: :show
  resource :locale, only: :update

  get "/home", to: "home#index", as: :home

  root to: "static#index"
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

class MoviesController < ApplicationController
  def index
    @data = {
      catalog: MovieMates::Library.new(
        user: current_user,
        sort_by: params[:sort_by],
        page: params[:page]
      ).as_json,
      sort_by: params[:sort_by],
    }
  end

  def create
    movie = MovieMates::Import::Librarian.
      new(tmdb_id: params[:tmdb_id], user: current_user).
      nominate_movie.
      movie

    flash[:notice] = t(".import_notice", title: movie.tmdb_profile.title)
    redirect_to movie_path(movie)
  end

  def show
    @movie = Picking::WatchablePresenter::Movie.new(
      slug: params[:slug],
      current_user:,
      country: I18n.locale
    ).as_json
  end

  def update
    Picking::LibraryVotes.new(group: current_user.group).mark_watched(
      slug: params[:slug],
      watched_user_ids: (params[:watched] || {}).keys.map(&:to_i)
    )

    redirect_to movie_path(params[:slug])
  end

  def destroy
    MovieNomination.
      joins(:group, :movie).
      find_by!(group: current_user.group, movies: {slug: params[:slug]}).
      destroy

    redirect_to movies_path
  end
end

app/views/movies/_catalog.html.haml
.row#catalog
  - catalog.fetch(:watchables).each_with_index do |watchable, index|
    .col-xs-12.col-sm-6.col-md-4.col-lg-3
      .panel.panel-default
        .panel-heading
          - year = watchable[:year] ? " (#{watchable.fetch(:year)})" : ''
          - path = watchable_type == "movie" ? movie_path(slug: watchable.fetch(:slug)) : tv_show_path(slug: watchable.fetch(:slug))
          = link_to("#{watchable.fetch(:title)}#{year}", path, 'data-watchable-title' => true)
        .panel-body
          .row
            .col-xs-5
              - if watchable[:poster]
                = image_tag(watchable.fetch(:poster), class: 'img-responsive poster')
            .col-xs-7
              .row.text-center
                .col-xs-4.text-warning.small
                  %span.glyphicon.glyphicon-star
                  %br
                  = watchable.fetch(:rating)
                - if watchable[:minutes]
                  .col-xs-5.text-info.small
                    %span.glyphicon.glyphicon-time
                    %br
                    = "#{watchable.fetch(:minutes) / 60}h #{watchable.fetch(:minutes) % 60}m"
                .col-xs-3.text-success.small
                  %span.glyphicon.glyphicon-comment
                  %br
                  = watchable.fetch(:comment_count)
              .card-break
              .row.text-center.no-gutters
                .col-xs-12
                  .btn.btn-xs.btn-frame.btn-block.btn-noclick.text-success{ type: 'button',
                                                                            'data-toggle' => 'tooltip',
                                                                            'data-placement' => 'top',
                                                                            title: ApplicationHelper.detailed_votes_list(watchable.fetch(:votes)) }
                    - watchable.fetch(:votes).map { |v| v.fetch(:opinion) }.tap do |opinions|
                      - ['yes', 'abstention', 'no', 'unknown', 'watched'].each do |opinion|
                        - count = opinions.count(opinion)
                        - next if count.zero?
                        %span
                          = icon_for_opinion(opinion)
                          = "x #{opinions.count(opinion)}"
                .col-xs-12
                  .btn.btn-xs.btn-frame.btn-block.btn-noclick.text-success{ type: 'button' }
                    = t('.movie_card.you')
                    .clearfix
                    .btn-group{ 'data-toggle' => 'buttons' }
                      = render('movies/vote_button', watchable_type: watchable_type, opinion: 'yes', button_classes: "btn-catalog-vote", current_user_vote: watchable.fetch(:current_user_vote), slug: watchable.fetch(:slug))
                      = render('movies/vote_button', watchable_type: watchable_type, opinion: 'no', button_classes: "btn-catalog-vote", current_user_vote: watchable.fetch(:current_user_vote), slug: watchable.fetch(:slug))
                      = render('movies/vote_button', watchable_type: watchable_type, opinion: 'abstention', button_classes: "btn-catalog-vote", current_user_vote: watchable.fetch(:current_user_vote), slug: watchable.fetch(:slug))

    - # These lines place a clearfix row for the different layouts, so that rows
    - # look always aligned even with cells with uneven heights
    - if (index + 1) % 2 == 0
      .clearfix.visible-sm-block
    - if (index + 1) % 3 == 0
      .clearfix.visible-md-block
    - if (index + 1) % 4 == 0
      .clearfix.visible-lg-block

#movie-details.modal.fade{ tabindex: -1, role: 'dialog', 'aria-labelledby' => 'movie-details' }
  .modal-dialog.modal-lg{ role: 'document' }
    .modal-content.main-background
      .modal-header
        %button.close{ type: 'button', 'data-dismiss' => 'modal', 'aria-label' => 'Close' }
          %span{ 'aria-hidden' => true } &times;
      .modal-body
      .modal-footer
        %button.btn.btn-default{ type: 'button', 'data-dismiss' => 'modal' }= t('.movie_card.close')

app/views/movies/_vote_button.html.haml
- glyphicon, color_class = case opinion
  - when "yes" then ["play", "text-success"]
  - when "no" then ["stop", "text-danger"]
  - when "abstention" then ["adjust", "text-warning"]
  - when "watched" then ["eye-open", "text-muted"]
  - when "unknown" then ["question-sign", "text-primary"]

= button_tag(type: "button", class: "btn btn-default #{button_classes} #{"active" if current_user_vote == opinion}", onclick: "MovieMates.Catalog.update_vote(this, '#{watchable_type}')") do
  = radio_button_tag("vote", opinion, current_user_vote == opinion, "data-current-user-opinion" => opinion)
  = hidden_field_tag("slug", slug)
  %span{class: "glyphicon glyphicon-#{glyphicon} #{color_class}", "data-opinion": opinion}

app/views/movies/index.html.haml
%section#library
  %h1= t('.title')

  .btn-group
    %button.btn.btn-default.dropdown-toggle{ type: 'button', 'data-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' }
      = t('.sort.button')
      %span.caret

    %ul.dropdown-menu
      %li= link_to(t('.sort.alphabetically_high'), movies_path(sort_by: 'alphabetically_high'))
      %li= link_to(t('.sort.alphabetically_low'), movies_path(sort_by: 'alphabetically_low'))
      %li= link_to(t('.sort.rating_high'), movies_path(sort_by: 'rating_high'))
      %li= link_to(t('.sort.rating_low'), movies_path(sort_by: 'rating_low'))
      %li= link_to(t('.sort.duration_high'), movies_path(sort_by: 'duration_high'))
      %li= link_to(t('.sort.duration_low'), movies_path(sort_by: 'duration_low'))
  %hr

  = render 'movies/catalog', catalog: @data.fetch(:catalog), watchable_type: "movie"

  %nav.text-center
    = link_to('< ' + t('.previous_page'), movies_path(page: @data.fetch(:catalog).fetch(:current_page) - 1, sort_by: @data.fetch(:sort_by)), class: 'btn btn-default') unless @data.fetch(:catalog).fetch(:current_page) - 1 <= 0
    = link_to(t('.next_page') + ' >', movies_path(page: @data.fetch(:catalog).fetch(:current_page) + 1, sort_by: @data.fetch(:sort_by)), class: 'btn btn-default') unless @data.fetch(:catalog).fetch(:current_page) + 1 > @data.fetch(:catalog).fetch(:total_pages)

app/views/movies/show.html.haml
.row
  .col-xs-12
    %h1
      = @movie.fetch(:title)
      - if @movie.key?(:year)
        = "(#{@movie.fetch(:year)})"
  .col-xs-12.col-sm-3
    = image_tag(@movie.fetch(:poster), class: 'img-responsive poster-edit') if @movie[:poster]
  .col-xs-12.col-sm-9
    .row.icons-row
      .col-xs-12
      = link_to(@movie.fetch(:url_imdb), target: :_blank, class: 'link-provider') do
        = image_tag('imdb_logo.png', class: 'img-responsive btn-provider', width: 70)
      = link_to(@movie.fetch(:url_tmdb), target: :_blank, class: 'link-provider') do
        = image_tag('tmdb_logo.png', class: 'img-responsive btn-provider', width: 70)
    %br/
    - if @movie[:contributor]
      = t('.added_by_html', contributor: @movie.fetch(:contributor))
    - if @movie[:minutes]
      |
      %span.glyphicon.glyphicon-time
      = "#{@movie.fetch(:minutes) / 60}h #{@movie.fetch(:minutes) % 60}m"
    |
    %span.glyphicon.glyphicon-star
    = @movie.fetch(:rating)
    - if @movie.fetch(:genres)
      |
      = @movie.fetch(:genres).join(", ")
    %br/
    %br/
    - if @movie.fetch(:currently_in_library)
      %h4= t(".votes")
      .row.text-center
        .col-xs-12.col-sm-4.col-md-3.space-below
          .btn-group{ 'data-toggle' => 'buttons', role: "group" }
            = render('movies/vote_button', watchable_type: "movie", opinion: 'yes', button_classes: "btn-lg", current_user_vote: @movie.fetch(:current_user_vote), slug: @movie.fetch(:slug))
            = render('movies/vote_button', watchable_type: "movie", opinion: 'no', button_classes: "btn-lg", current_user_vote: @movie.fetch(:current_user_vote), slug: @movie.fetch(:slug))
            = render('movies/vote_button', watchable_type: "movie", opinion: 'abstention', button_classes: "btn-lg", current_user_vote: @movie.fetch(:current_user_vote), slug: @movie.fetch(:slug))
        .col-xs-12.col-sm-4.col-md-3
          - @movie.fetch(:votes).each do |vote|
            = image_tag(vote.fetch(:user_pic) + "?sz=40", class: "img-circle", height: 40)
            = vote.fetch(:user_name)
            &#x27a1;
            = t("opinion.#{vote.fetch(:opinion)}")
            %br/
    %button.btn.btn-primary.btn-lg.space-above.space-below{ type: :button, "data-toggle": :collapse, "data-target": "#providers", "aria-expanded": false, "aria-controls": :providers }
      %span.glyphicon.glyphicon-film
      = t(".show_providers")
    #providers.collapse
      - if @movie.fetch(:providers).any?
        %table.table.table-striped.table-bordered.table-condensed
          %tr.text-center
            %th
            %th.text-center= t(".free")
            %th.text-center= t(".subscription")
            %th.text-center= t(".rent")
            %th.text-center= t(".buy")
            %th.text-center= t(".ads")
            %th.text-center= t(".cinema")
          - @movie.fetch(:providers).each do |provider|
            %tr
              %td.text-right
                = provider.fetch(:name)
                = image_tag(provider.fetch(:icon_url), height: 35)
              %td.text-center
                = format_offers_cell(provider, :free) { |offer| offer.fetch(:presentation_type) }
              %td.text-center
                = format_offers_cell(provider, :flatrate) { |offer| offer.fetch(:presentation_type) }
              %td.text-center
                = format_offers_cell(provider, :rent) { |offer| "#{offer.fetch(:presentation_type)} #{offer.fetch(:price).format}" }
              %td.text-center
                = format_offers_cell(provider, :buy) { |offer| "#{offer.fetch(:presentation_type)} #{offer.fetch(:price).format}" }
              %td.text-center
                = format_offers_cell(provider, :ads) { |offer| offer.fetch(:presentation_type) }
              %td.text-center
                = format_offers_cell(provider, :cinema) { |offer| offer.fetch(:presentation_type) }
      - else
        = t(".no_offers")
    %h4= t('.plot')
    = @movie.fetch(:plot)
    %br/
    %br/
    - if @movie[:trailer_youtube_id]
      %iframe.trailer{src: "https://www.youtube.com/embed/#{@movie.fetch(:trailer_youtube_id)}", frameborder: 0}
      %br/
      %br/
    - unless @movie.fetch(:currently_in_library)
      = form_tag(library_nominations_path(slug: @movie.fetch(:slug), watchable_type: "movie")) do
        = button_tag(class: 'btn btn-lg btn-primary') do
          <span class="glyphicon glyphicon-plus"></span>
          = t('.add_to_library')
  - if @movie.fetch(:currently_in_library)
    .col-xs-12.col-sm-9#comments
      %h2
        %span.glyphicon.glyphicon-bullhorn
        = t('.comments.title')
      %ul.list-group
        - @movie.fetch(:comments).each do |comment|
          %li.list-group-item.comment
            .header
              %span.author
                = image_tag(comment.fetch(:author_pic) + "?sz=25", class: "img-circle", height: 25)
                %strong= comment.fetch(:author_name)
              %span.timestamp{title: comment.fetch(:timestamp)}
                %span.glyphicon.glyphicon-time
                = t('.comments.time_ago', time: time_ago_in_words(comment.fetch(:timestamp)))
            .body
              = comment.fetch(:body)
      = form_tag(comments_path(slug: @movie.fetch(:slug), watchable_type: "movie")) do
        .form-group
          = text_area_tag('comment', nil, placeholder: t('.comments.placeholder'), class: 'form-control')
        .form-group
          = button_tag(class: 'btn btn-action') do
            %span.glyphicon.glyphicon-plus
            = t('.comments.submit')

  .col-xs-12
    - if @movie.fetch(:currently_in_library)
      = form_tag(movie_path(@movie.fetch(:slug)), method: :patch) do
        - @movie.fetch(:votes).each do |vote|
          .checkbox
            = label_tag("watched[#{vote.fetch(:user_id)}]") do
              = check_box_tag("watched[#{vote.fetch(:user_id)}]", '1', vote.fetch(:opinion) == "watched")
              = image_tag(vote.fetch(:user_pic) + "?sz=30", class: "img-circle", height: 30)
              = t('.watched.label', username: vote.fetch(:user_name))
        .row<
          .col-xs-12.btn-wrapper
            = submit_tag(t('.watched.submit'), class: 'btn btn-primary')

    .row<
      .col-xs-12.btn-wrapper
        - if @movie.fetch(:currently_in_library)
          = link_to(movie_path(@movie.fetch(:slug)),  method: :delete, class: 'btn btn-danger') do
            %span.glyphicon.glyphicon-trash
            = t('.remove')