config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  devise_for :users,
             skip: :registrations,
             controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  devise_scope :user do
    resource :registration,
             only: [:edit, :update],
             controller: "users/registrations",
             as: :user_registration

    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end

  resource :my_group, except: [:new, :edit, :create] do
    resources :invitations, only: [:create] do
      collection do
        get :commit
      end
    end
  end
  resources :groups, only: [:index]

  namespace :library do
    resources :nominations, only: [:create], param: :slug
  end

  resources :movies, except: [:new, :edit], param: :slug
  resources :tv_shows, except: [:new, :edit], param: :slug

  resources :votes, only: :update, param: :slug
  resources :comments, only: :create, param: :slug

  resource :pick, only: [:new, :create, :show]

  resource :search, only: :show
  resource :faq, only: :show
  resource :locale, only: :update

  get "/home", to: "home#index", as: :home

  root to: "static#index"
end

app/controllers/my_groups_controller.rb
# frozen_string_literal: true

class MyGroupsController < ApplicationController
  ShowGroup = Struct.new(:id, :name, :one_member?)
  def show
    @group = ShowGroup.new(
      current_group.id, current_group.name, current_group.users.count == 1
    )
  end

  def update
    current_group.update!(name: params[:name])

    redirect_to my_group_path, notice: t(".success_notice")
  end

  def destroy
    if current_group.users.count == 1
      current_group.implode

      sign_out(current_user)

      redirect_to root_path
    else
      MovieMates::Registration::GroupSplit.
        split_into_new_group(user: current_user)

      redirect_to my_group_path, notice: t(".success_notice")
    end
  end

  private

  helper_method def current_group
    current_user.group
  end
end

app/views/my_groups/_form.html.erb
<%= form_with(url: my_group_path, local: true, id: :group, method: :patch) do |form| %>
  <fieldset>
    <legend><%= t('.legend') %></legend>

    <div class="form-group">
      <%= form.label :group_name, t('.group_name'), for: :group_name %>
      <%= form.text_field :name, id: :group_name, value: group.name, class: 'form-control' %>
    </div>
  </fieldset>

  <%= form.submit(t('.submit'), class: 'btn btn-success') %>
<% end %>

app/views/my_groups/show.html.erb
<h1><%= @group.name %></h1>

<%= render 'form', group: @group %>

<h2><%= t('.invite.title') %></h2>
<%= form_with(url: my_group_invitations_path, id: :invitation) do |form| %>
  <div class="form-group">
    <%= form.label :invitation_emails, t('.invite.label'), for: :invitation_emails %>
    <%= form.text_field :emails,
                        id:          :invitation_emails,
                        class:       'form-control',
                        placeholder: t('.invite.placeholder') %>
  </div>

  <%= form.submit(t('.invite.submit'), class: 'btn btn-success') %>
<% end %>
<%- if @group.one_member? %>
  <%= form_with(url: my_group_path, method: :delete) do |form| %>
    <%= button_tag(
          class: 'btn btn-danger',
          data: { confirm: t('.implode.confirmation') }) do %>
      <span class="glyphicon glyphicon-trash"></span>
      <%= t('.implode.submit') %>
    <% end %>
  <% end %>
<% else %>
  <%= form_with(url: my_group_path, method: :delete) do |form| %>
    <%= button_tag(
          class: 'btn btn-danger',
          data: { confirm: t('.split.confirmation') }) do %>
      <span class="glyphicon glyphicon-trash"></span>
      <%= t('.split.submit') %>
    <% end %>
  <% end %>
<% end %>