config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  devise_for :users,
             skip: :registrations,
             controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  devise_scope :user do
    resource :registration,
             only: [:edit, :update],
             controller: "users/registrations",
             as: :user_registration

    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end

  resource :my_group, except: [:new, :edit, :create] do
    resources :invitations, only: [:create] do
      collection do
        get :commit
      end
    end
  end
  resources :groups, only: [:index]

  namespace :library do
    resources :nominations, only: [:create], param: :slug
  end

  resources :movies, except: [:new, :edit], param: :slug
  resources :tv_shows, except: [:new, :edit], param: :slug

  resources :votes, only: :update, param: :slug
  resources :comments, only: :create, param: :slug

  resource :pick, only: [:new, :create, :show]

  resource :search, only: :show
  resource :faq, only: :show
  resource :locale, only: :update

  get "/home", to: "home#index", as: :home

  root to: "static#index"
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }
    %title MovieMates
    = favicon_link_tag 'moviemates_logo.png'
    = csrf_meta_tags
    %link{ crossorigin: 'anonymous', href: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css', integrity: 'sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u', rel: 'stylesheet' }
    %link{ rel: 'stylesheet', href: 'https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css' }
    %meta{ charset: 'utf-8' }
    %meta{ content: 'IE=edge', 'http-equiv' => 'X-UA-Compatible' }
    %meta{ content: 'width=device-width, initial-scale=1', name: 'viewport' }
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{ crossorigin: 'anonymous', integrity: 'sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa', src: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' }
    %script{ src: 'https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js' }

  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{ 'aria-expanded' => 'false', 'data-target' => '#main-navbar-collapse', 'data-toggle' => 'collapse', type: 'button' }
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to('MovieMates', home_path, class: 'navbar-brand')
        #main-navbar-collapse.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = form_tag(search_path, method: :get, class: 'form-inline') do
                .input-group.nav-search
                  = text_field_tag(:term, '', class: 'form-control', placeholder: t('.search'))
                  .input-group-btn
                    = button_tag(title: 'Search', class: 'btn btn-default') do
                      %span.glyphicon.glyphicon-search

                = hidden_field_tag "watchable_type", "movie"
          %ul.nav.navbar-nav.navbar-right
            = content_tag(:li, class: active_when { request.path.starts_with?(pick_path) }) do
              = link_to(new_pick_path) do
                %span.glyphicon.glyphicon-map-marker
                = t('.pick')
            = content_tag(:li, class: active_when { request.path == movies_path }) do
              = link_to(movies_path) do
                %span.glyphicon.glyphicon-list
                = t('.library')
            = content_tag(:li, class: active_when { request.path == tv_shows_path }) do
              = link_to(tv_shows_path) do
                %span.glyphicon.glyphicon-list
                = t('.tv_show_library')
            = content_tag(:li, class: active_when { request.path == faq_path }) do
              = link_to(faq_path) do
                %span.glyphicon.glyphicon-question-sign
                = t('.help')
            %li.dropdown
              %a.dropdown-toggle{ 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', href: '#', role: 'button' }
                = t('name')
                %span.caret
              %ul.dropdown-menu
                - (AVAILABLE_COUNTRIES - [I18n.locale]).each do |locale|
                  %li.text-center
                    = form_tag(locale_path, method: :patch) do
                      = hidden_field_tag(:locale, locale)
                      = submit_tag(t('name', locale: locale), class: 'btn-link')
            %li.dropdown
              %a.dropdown-toggle{ 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', href: '#', role: 'button' }
                = image_tag(current_user.google_pic + "?sz=26", height: 26)
                = t('.greeting', username: current_user.name)
                %span.caret
              %ul.dropdown-menu
                = content_tag(:li) { link_to(t('.my_profile'), edit_user_registration_path) }
                = content_tag(:li) { link_to(t('.my_group'), my_group_path) }
                %li.divider{ role: 'separator' }
                = content_tag(:li, class: 'text-center') { button_to(t('.sign_out'), destroy_user_session_path, method: :delete, class: 'btn navbar-btn btn-danger') }

    .container-fluid
      - if notice
        .alert.alert-success.alert-dismissible{ role: 'alert' }
          %button.close{ 'data-dismiss' => 'alert', type: 'button' }
            %span{ 'aria-hidden' => true } &times;
          = notice
      - if alert
        .alert.alert-warning.alert-dismissible{ role: 'alert' }
          %button.close{ 'data-dismiss' => 'alert', type: 'button' }
            %span{ 'aria-hidden' => true } &times;
          = alert

      = link_to(image_tag('moviemates_banner.png', class: 'img-responsive logo-text'), home_path)

      = yield

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieMates</title>
    <%=  favicon_link_tag 'moviemates_logo.png' %>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.min.css"
          integrity="sha256-rFMLRbqAytD9ic/37Rnzr2Ycy/RlpxE5QH52h7VoIZo="
          crossorigin="anonymous" />

    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
          integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.0.13/css/brands.css"=
          integrity="sha384-VGCZwiSnlHXYDojsRqeMn3IVvdzTx5JEuHgqZ3bYLCLUBV8rvihHApoA1Aso2TZA"
          crossorigin="anonymous">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:creator" content="@Ferdy89" />
    <meta property="og:title" content="MovieMates" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="Find the right movie to watch with the right friends">
    <meta property="og:url" content="https://moviemates.party" />
    <meta property="og:image" content="https://moviemates.party/logo.png" />
    <%= stylesheet_link_tag 'static', media: 'all' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
            integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
            crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container-fluid">
      <% if notice %>
        <div class='alert alert-success alert-dismissible' role='alert'>
          <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class='alert alert-warning alert-dismissible' role='alert'>
          <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
          <%= alert %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>